// <auto-generated />
using System;
using FL_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FL_backend.Data.Migrations
{
    [DbContext(typeof(FLContext))]
    [Migration("20260621195515_InitialFlSchema")]
    partial class InitialFlSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fl")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FL_backend.Models.FlClientResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FlRoundId")
                        .HasColumnType("integer");

                    b.Property<int>("NumExamples")
                        .HasColumnType("integer");

                    b.Property<double>("TestF1")
                        .HasColumnType("double precision");

                    b.Property<double>("TrainF1")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FlRoundId");

                    b.ToTable("fl_client_result", "fl");
                });

            modelBuilder.Entity("FL_backend.Models.FlLocalBaseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumExamples")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("TestF1")
                        .HasColumnType("double precision");

                    b.Property<double>("TrainF1")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("fl_local_baseline", "fl");
                });

            modelBuilder.Entity("FL_backend.Models.FlRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("fl_round", "fl");
                });

            modelBuilder.Entity("FL_backend.Models.FlClientResult", b =>
                {
                    b.HasOne("FL_backend.Models.FlRound", "FlRound")
                        .WithMany("ClientResults")
                        .HasForeignKey("FlRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlRound");
                });

            modelBuilder.Entity("FL_backend.Models.FlRound", b =>
                {
                    b.Navigation("ClientResults");
                });
#pragma warning restore 612, 618
        }
    }
}
