# -*- coding: utf-8 -*-
"""final_robust_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UU7aVEN2Vu8D5F0DPR2IxA64eTwAwcdY
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW

# 1. إعداد الجهاز والميزات
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def inject_advanced_features(X):
    diff = np.diff(X, axis=1, prepend=X[:, :1, :])
    return np.concatenate([X, diff], axis=2)

# 2. كلاس النموذج النهائي iTransformer Ultra
class iTransformerUltra(nn.Module):
    def __init__(self, n_sensors, window_size=16, d_model=128, n_classes=3):
        super().__init__()
        self.enc_embedding = nn.Linear(window_size, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=8, dim_feedforward=512, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=4)
        self.classifier = nn.Sequential(nn.Linear(n_sensors * d_model, 256), nn.ReLU(), nn.Linear(256, n_classes))

    def forward(self, x):
        x = x.transpose(1, 2)
        x = self.enc_embedding(x)
        x = self.transformer_encoder(x)
        return self.classifier(x.reshape(x.size(0), -1))

# 3. دالة الخسارة الهجومية
class UltraPerformanceFocalLoss(nn.Module):
    def __init__(self, gamma=3.5):
        super().__init__()
        self.gamma = gamma
    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        return (((1 - pt) ** self.gamma) * ce_loss).mean()

# هذا هو الكود الأساسي الذي سيعمل عليه شريكك في المستودع
print("Federated iTransformer Model Ready for GitHub Deployment.")