services:
  fl_backend:
    build:
      context: .
      dockerfile: FL_backend/Dockerfile
    depends_on:
      - postgres
  postgres:
    image: postgres:17.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fl.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:

